import {
  Trophy,
  House,
  Users,
  CalendarBlank,
  GearSix,
  ClockCounterClockwise,
  ChartLineUp,
  CheckCircle,
  UploadSimple,
  DownloadSimple,
  WebhooksLogo,
  GraduationCap,
  BookOpen,
  Lightning,
  Medal,
  Newspaper,
  Megaphone,
  Gear,
  WhatsappLogo,
} from '@phosphor-icons/react'
import type { LayoutConfig } from './types'

export const adminConfig: LayoutConfig = {
  role: 'admin',
  roleLabel: 'Admin',
  baseHref: '/admin',
  allowedRoles: ['admin', 'superadmin'],
  defaultUserLabel: 'Admin',
  navItems: [
    { label: 'Dashboard', href: '/admin', icon: House },
    { label: 'Persetujuan', href: '/admin/approvals', icon: CheckCircle },
    { label: 'Analitik', href: '/admin/analytics', icon: ChartLineUp },
    { label: 'Turnamen', href: '/admin/tournaments', icon: Trophy },
    { label: 'Aturan', href: '/admin/rules', icon: BookOpen },
    { label: 'Tim', href: '/admin/teams', icon: Users },
    { label: 'Jadwal', href: '/admin/schedules', icon: CalendarBlank },
    { label: 'Sekolah', href: '/admin/schools', icon: GraduationCap },
    { label: 'Pengguna', href: '/admin/users', icon: Users },
    { label: 'Verifikasi', href: '/admin/submissions', icon: CheckCircle },
    { label: 'Import Peserta', href: '/admin/import', icon: UploadSimple },
    { label: 'Export Data', href: '/admin/export', icon: DownloadSimple },
    { label: 'Log Aktivitas', href: '/admin/activity', icon: ClockCounterClockwise },
    { label: 'Events', href: '/admin/events', icon: Medal },
    { label: 'Berita', href: '/admin/news', icon: Newspaper },
    { label: 'Pengumuman', href: '/admin/announcements', icon: Megaphone },
    { label: 'Broadcast WA', href: '/admin/broadcast', icon: WhatsappLogo },
    { label: 'Pengaturan Situs', href: '/admin/site-settings', icon: Gear },
    { label: 'Live Score', href: '/admin/live', icon: Lightning },
    { label: 'Webhooks', href: '/admin/webhooks', icon: WebhooksLogo },
    { label: 'Pengaturan', href: '/admin/settings', icon: GearSix },
  ],
}
